version: "3.7"

services:

  social:
    build: ./
    container_name: twitter_bot
    restart: always
    environment:
    - ACCESS_TOKEN=
    - TWEET_PRIVACY=unlisted
    - REPLY_PRIVACY=private
    - YEAR_OFFSET=15
    - PYTHONUNBUFFERED=1
    volumes:
      - ./files/:/twitterbot/files/
