version: "3.7"

services:

  social:
    image: milesbelli/twitter-time-capsule:latest
    networks:
      - ip6net
    build: ./
    container_name: twitter_bot
    restart: always
    environment:
    # Put the access token you get when you set up your app here (no quotes)
    - ACCESS_TOKEN=
    # Define privacy for tweets and replies independently. Options are public, unlisted, private, skip
    - TWEET_PRIVACY=unlisted
    - REPLY_PRIVACY=private
    # Set the offset in years that you want to go back. Must be integer greater than 0
    - YEAR_OFFSET=16
    # What's the name of the archive folder inside of the files directory
    - ARCHIVE_FOLDER=
    # Set account info. Use %Y to specify year.
    - PROFILE_NAME=
    - PROFILE_DESC=
    # Set timezone you want profile to be associated with
    - LOCAL_TZ=America/New_York
    # Set URL of the bot's instance
    - INSTANCE=
    # This is so the output logs work in Docker
    - PYTHONUNBUFFERED=1
    volumes:
    # Left hand side is directory outside the container, where
    # the output editor file and twitter archive will live
      - ./files/:/twitterbot/files/

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112
